source 'https://rubygems.org'

gem 'activesupport'
gem 'activerecord'
gem 'activerecord-postgresql-adapter'
gem 'bcrypt-ruby'
gem 'dalli'
gem 'em-websocket'
gem 'eventmachine'
gem 'haml'
gem 'hashie'
gem 'msgpack'
gem 'pg'
gem 'rack-rest_api_versioning'
gem 'redis'
gem 'em-hiredis'
gem 'sass'
gem 'scorched'
gem 'sprockets'
gem 'sshkey'
gem 'warden'
gem 'kgio'
gem 'coffee-script'
# gem 'faye'
gem 'thin'
gem 'mail'
gem 'omniauth'
gem 'omniauth-github'# , :git => 'git://github.com/intridea/omniauth-github.git'
gem 'msgpack'

group :development do
  gem 'foreman'
  gem 'shotgun'
  gem 'tux'
  gem 'bourbon'
  gem 'post_office'
end
