source 'https://rubygems.org'

gem 'activerecord'
gem 'activerecord-postgresql-adapter'
gem 'bcrypt-ruby'
gem 'dalli'
gem 'em-websocket'
gem 'eventmachine'
gem 'haml'
gem 'hashie'
gem 'msgpack'
gem 'pg'
gem 'rack-rest_api_versioning'
gem 'redis'
gem 'em-hiredis'
gem 'sass'
gem 'scorched'
gem 'sprockets'
gem 'sshkey'
gem 'warden'
gem 'kgio'
gem 'faye'
gem 'thin'

group :development do
  gem 'foreman'
  gem 'shotgun'
  gem 'tux'
end
