source 'https://rubygems.org'

gem 'rack'
gem 'rspec'
gem 'activesupport'
gem 'activerecord'
gem 'activerecord-postgresql-adapter'
gem 'activerecord-postgres-array'
gem 'bcrypt-ruby'
gem 'dalli'
gem 'em-websocket'
gem 'eventmachine'
gem 'haml'
gem 'hashie'
gem 'msgpack'
gem 'pg'
gem 'rack-rest_api_versioning'
gem 'redis'
gem 'em-hiredis'
gem 'therubyracer'
gem 'uglifier'
gem 'sass'
gem 'scorched'
gem 'stripe'
gem 'sprockets'
gem 'yui-compressor'
gem 'sshkey'
gem 'airbrake'
gem 'warden'
gem 'kgio'
gem 'coffee-script'
gem 'mina'
gem 'thin'
gem 'mail'
gem 'omniauth'
gem 'omniauth-github'
gem 'msgpack'
gem 'foreman'
gem 'tux'
gem 'daemons'
gem 'file-tail'
gem 'clockwork'
gem 'dragonfly'
gem 'typekit'
gem 'rack-cache', :require => 'rack/cache'

group :development do
  gem 'shotgun'
  gem 'bourbon'
  gem 'post_office'
end
